/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1-20190522110022+0000/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:27.0.1-jre")

    // Wikidata Toolkit
    implementation("org.wikidata.wdtk:wdtk-datamodel:0.9.0")
    implementation("org.wikidata.wdtk:wdtk-dumpfiles:0.9.0")
    implementation("org.wikidata.wdtk:wdtk-rdf:0.9.0")

    // For ZSTD dumps
    implementation("com.github.luben:zstd-jni:1.4.0-1")

    // logging implementation(
    runtimeOnly("org.slf4j:slf4j-simple:1.7.26")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application
    mainClassName = "io.github.bennofs.wdumper.App"
}
