/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1-20190522110022+0000/userguide/multi_project_builds.html
 */

rootProject.name = "wdumper"

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        jcenter()
        maven { url = uri("https://jitpack.io") }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "cz.habarta.typescript-generator") {
                // use own fork with patch for gradle api dependency
                // remove if https://github.com/vojtechhabarta/typescript-generator/pull/478 is merged & released
                useModule("com.github.bennofs.typescript-generator:typescript-generator-gradle-plugin:0e3cce7cddc3b57c953ebc799e6f8a7138807346")
            }
        }
    }
}
