"""zenodo: make upload_bytes be bigint

Revision ID: 15e17ac2f68f
Revises: a95ef06204fe
Create Date: 2019-08-18 14:56:11.878451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15e17ac2f68f'
down_revision = 'a95ef06204fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zenodo', 'uploaded_bytes',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zenodo', 'uploaded_bytes',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
