"""dump: add description column

Revision ID: 4784b7448cec
Revises: d64d77cf9c7f
Create Date: 2019-11-21 03:08:24.619796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4784b7448cec'
down_revision = 'd64d77cf9c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dump', sa.Column('description', sa.UnicodeText(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dump', 'description')
    # ### end Alembic commands ###
