"""run: add additional columns for statistics and version

Revision ID: 4cc940308e7b
Revises: 15e17ac2f68f
Create Date: 2019-11-18 17:31:46.011811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc940308e7b'
down_revision = '15e17ac2f68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('dump_items', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('run', sa.Column('dump_statements', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('run', sa.Column('tool_version', sa.Text(), nullable=True))
    op.add_column('run', sa.Column('wdtk_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'wdtk_version')
    op.drop_column('run', 'tool_version')
    op.drop_column('run', 'dump_statements')
    op.drop_column('run', 'dump_items')
    # ### end Alembic commands ###
