"""run: add column for dump datestamp

Revision ID: d64d77cf9c7f
Revises: 80b1a26a2b23
Create Date: 2019-11-18 21:49:08.176308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64d77cf9c7f'
down_revision = '80b1a26a2b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('dump_date', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'dump_date')
    # ### end Alembic commands ###
