"""remove dump completed_at column

Revision ID: dd5ce3d0a1a4
Revises: 43599d5cac35
Create Date: 2019-08-13 21:26:56.333420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd5ce3d0a1a4'
down_revision = '43599d5cac35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dump_completed_at', table_name='dump')
    op.drop_column('dump', 'completed_at')
    op.alter_column('zenodo', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zenodo', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.add_column('dump', sa.Column('completed_at', mysql.TIMESTAMP(), nullable=True))
    op.create_index('ix_dump_completed_at', 'dump', ['completed_at'], unique=False)
    # ### end Alembic commands ###
